name: Upload to Wiki

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  upload-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: Dwlad90/stylex-swc-plugin.wiki
          path: wiki
          token: ${{ secrets.WIKI_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN }}

      - name: Copy files to wiki
        run: |
          rm -rf .git
          cp -rf ./*.md wiki/
          cd wiki

      - name: Commit and push changes
        run: |
          cd wiki
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Update wiki from main repository" || echo "No changes to commit"
          git push origin HEAD:master